### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [12]:
vector = np.random.rand(10,1)
print("Vector:")
print(vector)
print("\nShape of the vector:")
print(vector.shape)

Vector:
[[0.59312871]
 [0.31952634]
 [0.37289307]
 [0.31206612]
 [0.99602564]
 [0.99233508]
 [0.10979588]
 [0.51697491]
 [0.98916582]
 [0.31902289]]

Shape of the vector:
(10, 1)


In [18]:
lst = np.arange(11, 38, 3)
matrix = lst.reshape(3,3)
print("Matrix:")
print(matrix)
print("\nShape of the matrix:")
print(matrix.shape)

Matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

Shape of the matrix:
(3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [22]:
vector2 = np.round(vector + 10, 2)
vector2

array([[10.59],
       [10.32],
       [10.37],
       [10.31],
       [11.  ],
       [10.99],
       [10.11],
       [10.52],
       [10.99],
       [10.32]])

In [23]:
matrix2 = matrix * 2
matrix2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [25]:
new_vector = vector ** 2
new_vector

array([[0.35180166],
       [0.10209708],
       [0.13904925],
       [0.09738527],
       [0.99206709],
       [0.98472891],
       [0.01205514],
       [0.26726306],
       [0.97844903],
       [0.1017756 ]])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [26]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [30]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [31]:
np.dot(result_matrix, C)

array([[0.5202],
       [0.2846]])

In [32]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [36]:
result_matrix_transposed = result_matrix.T
result_matrix_transposed

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [37]:
vector_transposed = vector.T
vector_transposed

array([[0.59312871, 0.31952634, 0.37289307, 0.31206612, 0.99602564,
        0.99233508, 0.10979588, 0.51697491, 0.98916582, 0.31902289]])

Є зміна - вектор-стовпець став вектором-рядком

In [38]:
column_vector = np.expand_dims(vector, axis=1)
column_vector

array([[[0.59312871]],

       [[0.31952634]],

       [[0.37289307]],

       [[0.31206612]],

       [[0.99602564]],

       [[0.99233508]],

       [[0.10979588]],

       [[0.51697491]],

       [[0.98916582]],

       [[0.31902289]]])

In [39]:
column_vector.shape

(10, 1, 1)

numpy.expand_dims додає ще один вимір до vector

In [41]:
column_vector_transposed = column_vector.T
print("column_vector_transposed:")
print(column_vector_transposed)
print("\nрозмір column_vector_transposed:")
print(column_vector_transposed.shape)

column_vector_transposed:
[[[0.59312871 0.31952634 0.37289307 0.31206612 0.99602564 0.99233508
   0.10979588 0.51697491 0.98916582 0.31902289]]]

розмір column_vector_transposed:
(1, 1, 10)
